#BFCLIENT Parameters
localport :=4115
timeout :=3

#other clients:
ipaddress1 :=127.0.0.1
port1 :=4116
weight :=5.0

bfclient:
	python bfclient.py $(localport) $(timeout) $(ipaddress1) $(port1) $(weight)
clean:
	rm *.pyc 
